# Streamlit
FROM python:3.10-slim

WORKDIR /app

COPY requirements.2.txt .
RUN pip install -r requirements.2.txt

COPY app.py .
COPY ask_for_house_price.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]